### ISSUE TITLE
Dialogs broken with nifty-dialog v1.1.0

### ISSUE THREAD

**Issue by m-codebastards** [tryshoppe/core#150]
@adamcooke new version of nifty-dialog 1.1.0 has broken dialogs in shoppe. Please advise.
![produkty_-_shoppe](https://cloud.githubusercontent.com/assets/9202596/5605863/19a538c0-9414-11e4-99cc-a09f6668a1b7.png)

**Comment by squidbits** [comment]
FWIW, I'm running into this as well. The margin-left seems to be the culprit. If you remove the minus (margin-left: 350px), then it displays properly.

<div class="niftyDialog  ajax" id="niftyDialog-ajax" style="z-index: 2001; width: 700px; margin-left: -350px; display: block;">
